// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  form: dynamic(() => import("./Form")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
};
