import type { Metadata } from "next";
import { Bubblegum_Sans, Nunito } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const bubblegumSans = Bubblegum_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bubblegum",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${bubblegumSans.variable} ${nunito.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <Nav />
        {children}
      </body>
    </html>
  );
}
